Class Prova.Data.CandidatoCurso Extends (%Persistent, %XML.Adaptor)
{

Storage Default
{
<Data name="CandidatoCursoDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Prova.Data.CandidatoCursoD</DataLocation>
<DefaultData>CandidatoCursoDefaultData</DefaultData>
<IdLocation>^Prova.Data.CandidatoCursoD</IdLocation>
<IndexLocation>^Prova.Data.CandidatoCursoI</IndexLocation>
<StreamLocation>^Prova.Data.CandidatoCursoS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
