Class Prova.Data.Curso Extends (%Persistent, %XML.Adaptor)
{

Storage Default
{
<Data name="CursoDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Prova.Data.CursoD</DataLocation>
<DefaultData>CursoDefaultData</DefaultData>
<IdLocation>^Prova.Data.CursoD</IdLocation>
<IndexLocation>^Prova.Data.CursoI</IndexLocation>
<StreamLocation>^Prova.Data.CursoS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
